theme: minima
title: QuantBrain
description: Let's Quantum!

author:
  name: Mehmet Niyazi Kayi
  email: mehmet.nyz.7@gmail.com
  linkedin: "https://www.linkedin.com/in/mehmet-niyazi-kayÄ±-760b73151"

url: "https://mehmetniyazikayi.github.io"
baseurl: ""

# Google Analytics
google_analytics: G-XXXXXXXXXX  # Replace with your actual Google Analytics 4 measurement ID

exclude:
  - README.md

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Sensible defaults that DO NOT break Minima
defaults:
  # Posts get the blog layout automatically
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: project

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
    #  - jekyll-feed
  - jekyll-paginate


paginate: 5
paginate_path: "/blog/page:num"

header_pages:
   - about.md
   - projects.md
   - tags.md

