theme: minima
title: QuantBrain
description: Let's Quantum!

author:
  name: Mehmet Niyazi Kayi
  email: mehmetniyazikayi@gmail.com

url: "https://mehmetniyazikayi.github.io"
baseurl: ""

exclude:
  - README.md

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Sensible defaults that DO NOT break Minima
defaults:
  # Posts get the blog layout automatically
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: project

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate


paginate: 5
paginate_path: "/blog/page:num"

header_pages:
   - about.md
   - projects.md
   - tags.md

